development:
  adapter: postgresql
  encoding: unicode
  database: asocial-feed_development
  pool: 5
  timeout: 5000
  username: asocial-feed

test:
  adapter: postgresql
  encoding: unicode
  database: asocial-feed_test
  pool: 5
  timeout: 5000
  username: asocial-feed

production:
  adapter: postgresql
  encoding: unicode
  database: asocial-feed_production
  pool: 5
  timeout: 5000
